server:
  port: 8080
  servlet:
    context-path: /zdata-sycm
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sycm?characterEncoding=utf-8&useSSL=false
      username: xxxxxx
      password: xxxxxx
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  jmx:
    enabled: false
  redis:
    database: 1
    host: 39.98.44.185
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000
  cache:
    type: redis
  thymeleaf:
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
    cache: true
    mode: HTML 
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:com/zdata/sycm/mapper/*.xml
  type-aliases-package: com.zdata.sycm.model
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    #二级缓存
    cache-enabled: true

# pagehelper   
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: false
    params: count=countSql

logging:
  level:
    com.zdata.sycm.dao : info